"""Curated, per-role content for the programmatic /resume-examples/{role} pages.

Each entry is hand-written (NOT auto-generated) so every page carries real,
unique, useful content — keywords, skills, example bullet points, and common
mistakes — and never reads as a thin/doorway page. To add a role, append a dict
following the same shape. `blog` links to the matching in-depth blog post when
one exists (interlinking strengthens both pages).

Shape:
    slug: {
        "role": display name,
        "title": <SEO <title>>,
        "description": <meta description, ~150 chars>,
        "intro": <1-2 sentence lead paragraph>,
        "skills": [..top hard skills..],
        "keywords": [..ATS keywords recruiters scan for..],
        "bullets": [..example resume bullet points..],
        "mistakes": [..common resume mistakes for this role..],
        "blog": <blog slug or None>,
    }
"""

ROLE_SEO: dict[str, dict] = {
    "backend-developer": {
        "role": "Backend Developer",
        "title": "Backend Developer Resume Example & Guide (2026) | theTailorCV",
        "description": "A backend developer resume example with ATS keywords, the right skills, and example bullet points that prove API, database, and system-design impact.",
        "intro": "A strong backend developer resume proves you can design reliable APIs, model data well, and build systems that handle real production load — with specifics, not buzzwords.",
        "skills": ["Python", "Node.js", "Java", "Go", "REST & GraphQL APIs", "PostgreSQL", "Redis", "Docker", "Kubernetes", "AWS"],
        "keywords": ["REST API", "microservices", "database design", "system design", "CI/CD", "caching", "message queues", "scalability", "unit testing", "Docker"],
        "bullets": [
            "Designed and shipped a REST API handling 2M+ requests/day, cutting p95 latency 40% with Redis caching and query optimization.",
            "Migrated a monolith to 6 microservices, reducing deploy time from 45 min to 6 min via containerized CI/CD.",
            "Modeled and indexed a PostgreSQL schema for a payments service, eliminating N+1 queries and improving throughput 3x.",
            "Built an event-driven pipeline with Kafka processing 500K events/hour with at-least-once delivery guarantees.",
        ],
        "mistakes": [
            "Listing languages without showing scale, performance, or system-design decisions.",
            "No metrics — recruiters can't tell a toy project from production work.",
            "Burying impact under tech jargon instead of leading with the outcome.",
        ],
        "blog": "backend-developer-resume-2026",
    },
    "frontend-developer": {
        "role": "Frontend Developer",
        "title": "Frontend Developer Resume Example & Guide (2026) | theTailorCV",
        "description": "A frontend developer resume example with React/TypeScript keywords, key skills, and bullet points that show UI craft, performance, and accessibility.",
        "intro": "A frontend resume should prove you build fast, accessible, polished interfaces — and that you understand the product, not just the pixels.",
        "skills": ["React", "TypeScript", "Next.js", "JavaScript", "HTML & CSS", "Tailwind", "Redux", "Jest", "Web performance", "Accessibility (a11y)"],
        "keywords": ["React", "TypeScript", "responsive design", "web performance", "accessibility", "component library", "state management", "REST API", "unit testing", "CI/CD"],
        "bullets": [
            "Rebuilt the checkout flow in React + TypeScript, lifting conversion 18% and cutting Largest Contentful Paint from 4.1s to 1.6s.",
            "Built a reusable component library (40+ components) adopted across 5 teams, halving new-feature build time.",
            "Improved Lighthouse accessibility score from 72 to 98 by fixing focus management, ARIA roles, and color contrast.",
            "Cut JavaScript bundle size 35% via code-splitting and lazy loading, improving Time to Interactive on mobile.",
        ],
        "mistakes": [
            "Showing frameworks but no live links — for frontend, the work should be clickable.",
            "Ignoring performance and accessibility, which senior reviewers specifically look for.",
            "Generic 'built responsive websites' with no metrics or product context.",
        ],
        "blog": "frontend-developer-resume-2026",
    },
    "full-stack-developer": {
        "role": "Full Stack Developer",
        "title": "Full Stack Developer Resume Example & Guide (2026) | theTailorCV",
        "description": "A full stack developer resume example showing end-to-end skill — frontend, backend, and deployed apps — with ATS keywords and strong bullet points.",
        "intro": "A full stack resume must prove range AND depth: polished UI, solid backend, and shipped, working products you can point to.",
        "skills": ["React", "Node.js", "TypeScript", "Python", "PostgreSQL", "MongoDB", "REST & GraphQL", "Docker", "AWS", "CI/CD"],
        "keywords": ["full stack", "React", "Node.js", "REST API", "database design", "deployment", "Docker", "system design", "testing", "MERN"],
        "bullets": [
            "Built and deployed a SaaS dashboard end-to-end (React, Node, PostgreSQL) used by 1,200+ paying users.",
            "Implemented JWT auth, role-based access, and Stripe billing, taking the product from prototype to revenue.",
            "Set up Dockerized CI/CD on AWS, enabling zero-downtime deploys multiple times per day.",
            "Owned a feature from database schema to UI, shipping it in 2 weeks against a 4-week estimate.",
        ],
        "mistakes": [
            "Claiming 'full stack' but only showing one side in the bullets.",
            "No deployed/live projects — full stack is judged on shipped products.",
            "Listing every technology ever touched instead of the ones you're strong in.",
        ],
        "blog": "full-stack-developer-resume-2026",
    },
    "data-analyst": {
        "role": "Data Analyst",
        "title": "Data Analyst Resume Example & Guide (2026) | theTailorCV",
        "description": "A data analyst resume example with SQL, Python, and dashboard keywords, key skills, and bullet points framed around business impact — not just tools.",
        "intro": "A data analyst resume should show you turn data into decisions: clean analysis, clear dashboards, and recommendations the business actually used.",
        "skills": ["SQL", "Python", "Excel", "Tableau", "Power BI", "Pandas", "Statistics", "A/B testing", "Data visualization", "ETL"],
        "keywords": ["SQL", "Python", "Tableau", "Power BI", "data visualization", "A/B testing", "dashboards", "KPIs", "statistical analysis", "stakeholder reporting"],
        "bullets": [
            "Built a Tableau dashboard tracking 12 KPIs that became the weekly source of truth for a 30-person sales org.",
            "Wrote SQL to identify a churn driver that, once fixed, retained an estimated ₹40L in annual revenue.",
            "Ran an A/B test on onboarding that lifted activation 11%, validated to 95% significance.",
            "Automated a manual Excel report with a Python pipeline, saving the team ~10 hours per week.",
        ],
        "mistakes": [
            "Listing tools (SQL, Tableau) without tying any analysis to a business outcome.",
            "No numbers — a data resume with no metrics is a red flag.",
            "Describing tasks ('pulled reports') instead of insights and decisions driven.",
        ],
        "blog": "data-analyst-resume-2026",
    },
    "data-scientist": {
        "role": "Data Scientist",
        "title": "Data Scientist Resume Example & Guide (2026) | theTailorCV",
        "description": "A data scientist resume example with ML keywords, core skills, and bullet points framed around business impact and deployed models — not just accuracy.",
        "intro": "A data scientist resume should prove business impact: models that shipped, decisions they changed, and the metrics that moved — not just notebooks and accuracy scores.",
        "skills": ["Python", "SQL", "scikit-learn", "PyTorch", "Pandas", "Statistics", "Machine Learning", "MLflow", "Feature engineering", "A/B testing"],
        "keywords": ["machine learning", "Python", "deep learning", "model deployment", "feature engineering", "A/B testing", "NLP", "statistics", "MLOps", "experimentation"],
        "bullets": [
            "Built a churn model (AUC 0.89) deployed to production that cut churn 9% via targeted retention offers.",
            "Engineered features and trained a demand-forecasting model that reduced overstock costs 14%.",
            "Shipped an NLP pipeline classifying 50K support tickets/day, automating 30% of first-response routing.",
            "Designed and analyzed experiments end-to-end, replacing gut-feel launches with statistically valid decisions.",
        ],
        "mistakes": [
            "Showing only Kaggle/notebook accuracy with no deployed, business-facing impact.",
            "Listing every algorithm instead of the few that drove results.",
            "No mention of experimentation or how models changed a real decision.",
        ],
        "blog": "data-scientist-resume-2026",
    },
    "data-engineer": {
        "role": "Data Engineer",
        "title": "Data Engineer Resume Example & Guide (2026) | theTailorCV",
        "description": "A data engineer resume example with pipeline, warehouse, and cloud keywords, plus bullet points that show reliable, scalable data infrastructure.",
        "intro": "A data engineer resume should prove you build reliable, scalable pipelines and data platforms the whole company depends on.",
        "skills": ["Python", "SQL", "Spark", "Airflow", "dbt", "Kafka", "Snowflake", "AWS", "ETL/ELT", "Data modeling"],
        "keywords": ["ETL", "data pipeline", "Spark", "Airflow", "data warehouse", "Kafka", "dbt", "Snowflake", "data modeling", "streaming"],
        "bullets": [
            "Built Airflow pipelines processing 2TB/day with 99.9% on-time delivery and automated data-quality checks.",
            "Migrated batch ETL to Spark, cutting nightly processing from 6 hours to 45 minutes.",
            "Designed a Snowflake warehouse and dbt models that became the analytics layer for 8 teams.",
            "Built a Kafka streaming pipeline enabling near-real-time dashboards (sub-minute latency).",
        ],
        "mistakes": [
            "Listing tools without showing scale (volume, latency, reliability).",
            "No mention of data quality or pipeline observability.",
            "Confusing analyst work with engineering — show infra you built and own.",
        ],
        "blog": "data-engineer-resume-2026",
    },
    "devops-engineer": {
        "role": "DevOps Engineer",
        "title": "DevOps Engineer Resume Example & Guide (2026) | theTailorCV",
        "description": "A DevOps engineer resume example with CI/CD, Kubernetes, and cloud keywords, plus bullet points that show reliability, automation, and cost wins.",
        "intro": "A DevOps resume should prove you make shipping fast and systems reliable: automation, CI/CD, observability, and measurable uptime and cost wins.",
        "skills": ["Kubernetes", "Docker", "Terraform", "AWS", "CI/CD", "Linux", "Prometheus", "Ansible", "Python", "GitOps"],
        "keywords": ["CI/CD", "Kubernetes", "Terraform", "Docker", "infrastructure as code", "monitoring", "AWS", "automation", "reliability", "SRE"],
        "bullets": [
            "Built Terraform IaC for the full AWS stack, making environment provisioning a 10-minute, repeatable process.",
            "Cut deploy time 80% with a GitOps CI/CD pipeline and automated rollbacks.",
            "Reduced cloud spend 28% by right-sizing and autoscaling Kubernetes workloads.",
            "Set up Prometheus/Grafana monitoring and on-call alerts, improving uptime to 99.95%.",
        ],
        "mistakes": [
            "Listing tools without uptime, deploy-frequency, or cost metrics.",
            "No infrastructure-as-code or automation evidence.",
            "Ignoring reliability/observability, the heart of the role.",
        ],
        "blog": "devops-engineer-resume-2026",
    },
    "cloud-engineer": {
        "role": "Cloud Engineer",
        "title": "Cloud Engineer Resume Example & Guide (2026) | theTailorCV",
        "description": "A cloud engineer resume example with AWS/Azure keywords, core skills, and bullet points showing scalable, secure, cost-efficient cloud architecture.",
        "intro": "A cloud engineer resume should show you design secure, scalable, cost-efficient cloud architecture — with the certifications and metrics to back it.",
        "skills": ["AWS", "Azure", "Terraform", "Kubernetes", "Docker", "Networking", "IAM & security", "CloudFormation", "Python", "Cost optimization"],
        "keywords": ["AWS", "Azure", "cloud architecture", "Terraform", "Kubernetes", "IAM", "VPC", "cost optimization", "high availability", "serverless"],
        "bullets": [
            "Architected a multi-AZ AWS environment achieving 99.99% availability for a customer-facing API.",
            "Reduced monthly cloud bill 32% through reserved instances, autoscaling, and storage tiering.",
            "Implemented least-privilege IAM and VPC segmentation, passing a SOC 2 security audit.",
            "Migrated 20+ services to serverless (Lambda), cutting idle infrastructure cost to near zero.",
        ],
        "mistakes": [
            "No certifications listed (AWS/Azure certs are strong ATS and recruiter signals).",
            "Listing services without architecture decisions or cost/availability outcomes.",
            "Ignoring security — IAM and networking are core to the role.",
        ],
        "blog": "cloud-engineer-resume-2026",
    },
    "cybersecurity-engineer": {
        "role": "Cybersecurity Engineer",
        "title": "Cybersecurity Engineer Resume Example & Guide (2026) | theTailorCV",
        "description": "A cybersecurity engineer resume example with security keywords, certifications, and bullet points that show real risk reduction and incident response.",
        "intro": "A cybersecurity resume should prove you reduce real risk: vulnerabilities closed, incidents handled, and controls that passed audits.",
        "skills": ["SIEM", "Penetration testing", "Incident response", "Network security", "Python", "Vulnerability management", "IAM", "Cloud security", "Threat detection", "Compliance"],
        "keywords": ["incident response", "penetration testing", "SIEM", "vulnerability management", "threat detection", "SOC", "network security", "compliance", "IAM", "risk assessment"],
        "bullets": [
            "Led incident response for a credential-stuffing attack, containing it in under 30 minutes with zero data loss.",
            "Ran quarterly penetration tests and remediated 120+ findings, cutting critical vulnerabilities 70%.",
            "Tuned SIEM detection rules, reducing false positives 45% and surfacing 3 real threats in month one.",
            "Implemented MFA and least-privilege IAM across 200+ accounts ahead of a SOC 2 audit.",
        ],
        "mistakes": [
            "No certifications (Security+, OSCP, CISSP) — recruiters filter on these.",
            "Vague 'monitored security' bullets with no incidents, findings, or risk reduction.",
            "Listing tools without showing how they reduced actual risk.",
        ],
        "blog": "cybersecurity-engineer-resume-2026",
    },
    "android-developer": {
        "role": "Android Developer",
        "title": "Android Developer Resume Example & Guide (2026) | theTailorCV",
        "description": "An Android developer resume example with Kotlin/Jetpack keywords, key skills, and bullet points that show shipped apps, performance, and ratings.",
        "intro": "An Android resume should prove you ship polished apps users keep: Kotlin, Jetpack, performance, and Play Store results.",
        "skills": ["Kotlin", "Java", "Jetpack Compose", "Android SDK", "MVVM", "Coroutines", "Retrofit", "Room", "Unit testing", "CI/CD"],
        "keywords": ["Kotlin", "Jetpack Compose", "Android SDK", "MVVM", "REST API", "coroutines", "Play Store", "unit testing", "performance", "material design"],
        "bullets": [
            "Shipped a Kotlin + Jetpack Compose app to 500K+ installs with a 4.6★ Play Store rating.",
            "Cut app cold-start time 35% and reduced ANRs to under 0.2% through profiling and optimization.",
            "Migrated the UI to Jetpack Compose, removing 40% of legacy XML and speeding feature delivery.",
            "Built an offline-first sync layer with Room + WorkManager, improving retention in low-connectivity regions.",
        ],
        "mistakes": [
            "No published apps or Play Store links — Android work should be downloadable.",
            "Still showing only Java/XML with no modern Kotlin/Compose.",
            "No metrics on crashes, ratings, performance, or installs.",
        ],
        "blog": "android-developer-resume-2026",
    },
    "business-analyst": {
        "role": "Business Analyst",
        "title": "Business Analyst Resume Example & Guide (2026) | theTailorCV",
        "description": "A business analyst resume example with requirements, SQL, and stakeholder keywords, plus bullet points framed around measurable business outcomes.",
        "intro": "A business analyst resume should show you bridge business and tech: clear requirements, data-backed recommendations, and decisions that moved metrics.",
        "skills": ["Requirements gathering", "SQL", "Excel", "Power BI", "Stakeholder management", "Process mapping", "Agile", "JIRA", "Data analysis", "Documentation"],
        "keywords": ["requirements gathering", "stakeholder management", "SQL", "process improvement", "Agile", "user stories", "data analysis", "BRD", "gap analysis", "KPIs"],
        "bullets": [
            "Gathered and documented requirements for a billing revamp that reduced invoice errors 22%.",
            "Mapped and streamlined an approval workflow, cutting cycle time from 5 days to 1.",
            "Built Power BI reports that gave leadership real-time visibility and informed a ₹2Cr budget decision.",
            "Wrote user stories and acceptance criteria for 3 Agile teams, improving sprint predictability.",
        ],
        "mistakes": [
            "Listing 'requirements gathering' with no measurable business outcome.",
            "No data tools (SQL/BI) when most BA roles now expect them.",
            "Describing duties instead of decisions influenced and metrics moved.",
        ],
        "blog": "business-analyst-resume-2026",
    },
    "product-manager": {
        "role": "Product Manager",
        "title": "Product Manager Resume Example & Guide (2026) | theTailorCV",
        "description": "A product manager resume example with PM keywords, core skills, and bullet points framed around outcomes — adoption, retention, and revenue — not features.",
        "intro": "A product manager resume should lead with outcomes, not features: what you shipped, who it helped, and the metric it moved.",
        "skills": ["Product strategy", "Roadmapping", "User research", "A/B testing", "SQL", "Analytics", "Agile/Scrum", "Stakeholder management", "Prioritization", "Go-to-market"],
        "keywords": ["product strategy", "roadmap", "user research", "A/B testing", "KPIs", "stakeholder management", "go-to-market", "analytics", "prioritization", "product lifecycle"],
        "bullets": [
            "Owned a feature from discovery to launch that grew weekly active users 23% in one quarter.",
            "Ran user research and A/B tests that killed two low-value features and refocused the roadmap on retention.",
            "Defined and tracked North Star metrics, aligning 3 squads around activation and reducing churn 8%.",
            "Led go-to-market for a paid tier that reached ₹1Cr ARR within six months of launch.",
        ],
        "mistakes": [
            "Listing features shipped without the outcomes they drove.",
            "No metrics — PM resumes live or die on impact numbers.",
            "Taking sole credit; strong PM bullets show influence across teams.",
        ],
        "blog": None,
    },
    "digital-marketing": {
        "role": "Digital Marketing Specialist",
        "title": "Digital Marketing Resume Example & Guide (2026) | theTailorCV",
        "description": "A digital marketing resume example with SEO, paid ads, and analytics keywords, plus bullet points tied to traffic, leads, and ROI.",
        "intro": "A digital marketing resume should be all about results: traffic, leads, conversions, and ROI — with the channels and tools that delivered them.",
        "skills": ["SEO", "Google Ads", "Meta Ads", "Google Analytics", "Content marketing", "Email marketing", "SEM", "Conversion optimization", "Social media", "HubSpot"],
        "keywords": ["SEO", "Google Ads", "PPC", "Google Analytics", "conversion rate", "lead generation", "content marketing", "email marketing", "ROAS", "campaign management"],
        "bullets": [
            "Grew organic traffic 140% in 8 months through an SEO content strategy and technical fixes.",
            "Managed a ₹15L/month Google Ads budget at a 4.2x ROAS, beating target by 30%.",
            "Lifted email click-through 35% via segmentation and A/B-tested subject lines.",
            "Cut cost-per-lead 26% by reallocating spend to the highest-converting channels.",
        ],
        "mistakes": [
            "No metrics (traffic, ROAS, CPL) — marketing resumes need hard numbers.",
            "Listing channels without the results they produced.",
            "Ignoring analytics tools that prove you measure what you run.",
        ],
        "blog": "digital-marketing-resume-2026",
    },
    "financial-analyst": {
        "role": "Financial Analyst",
        "title": "Financial Analyst Resume Example & Guide (2026) | theTailorCV",
        "description": "A financial analyst resume example with modeling, Excel, and forecasting keywords, plus bullet points that show analysis driving real decisions.",
        "intro": "A financial analyst resume should show rigor and impact: models you built, forecasts you sharpened, and the decisions your analysis informed.",
        "skills": ["Financial modeling", "Excel", "SQL", "Forecasting", "Valuation", "Power BI", "Budgeting", "Variance analysis", "Accounting", "Data analysis"],
        "keywords": ["financial modeling", "forecasting", "variance analysis", "Excel", "valuation", "budgeting", "FP&A", "SQL", "DCF", "reporting"],
        "bullets": [
            "Built a 3-statement model and DCF that supported a ₹50Cr acquisition decision.",
            "Improved forecast accuracy from 82% to 94% by rebuilding the driver-based revenue model.",
            "Automated monthly variance reporting in Excel + SQL, saving 12 hours per close.",
            "Identified ₹3Cr in cost savings through a margin analysis presented to the CFO.",
        ],
        "mistakes": [
            "Listing 'financial analysis' without models built or decisions influenced.",
            "No metrics on accuracy, savings, or deal size.",
            "Weak Excel/SQL signals when both are baseline expectations.",
        ],
        "blog": "financial-analyst-resume-2026",
    },
    "graphic-designer": {
        "role": "Graphic Designer",
        "title": "Graphic Designer Resume Example & Guide (2026) | theTailorCV",
        "description": "A graphic designer resume example with design-tool keywords, key skills, and bullet points that show business impact and a link to your portfolio.",
        "intro": "A graphic designer resume should pair a strong portfolio link with bullets that show your work drove real results — not just 'designed assets'.",
        "skills": ["Adobe Photoshop", "Illustrator", "Figma", "InDesign", "Branding", "Typography", "Layout design", "UI design", "Motion graphics", "Brand identity"],
        "keywords": ["Adobe Creative Suite", "Figma", "branding", "typography", "visual design", "UI design", "brand identity", "layout", "Photoshop", "Illustrator"],
        "bullets": [
            "Redesigned the brand identity and assets, contributing to a 19% lift in landing-page conversion.",
            "Produced 200+ social creatives that grew engagement 60% over two quarters.",
            "Built a Figma design system that cut design-to-handoff time 40% across the team.",
            "Designed packaging that helped a product win shelf space in 3 national retailers.",
        ],
        "mistakes": [
            "No portfolio link — for designers, the work must be one click away.",
            "Listing tools without showing impact on the business or brand.",
            "A cluttered, hard-to-scan resume that contradicts the craft.",
        ],
        "blog": "graphic-designer-resume-2026",
    },
    "accountant": {
        "role": "Accountant",
        "title": "Accountant Resume Example & Guide (2026) | theTailorCV",
        "description": "An accountant resume example with accounting, reconciliation, and compliance keywords, plus bullet points that show accuracy, savings, and efficiency.",
        "intro": "An accountant resume should signal accuracy, compliance, and efficiency: clean books, faster closes, and savings or errors caught.",
        "skills": ["Accounts payable/receivable", "Reconciliation", "GST & tax", "Excel", "Tally", "QuickBooks", "Financial reporting", "Auditing", "Payroll", "GAAP"],
        "keywords": ["accounts payable", "reconciliation", "financial reporting", "GST", "tax compliance", "auditing", "Excel", "month-end close", "QuickBooks", "GAAP"],
        "bullets": [
            "Cut month-end close from 8 days to 4 by standardizing reconciliations and Excel automation.",
            "Reconciled 15+ accounts monthly with 100% accuracy across two audit cycles.",
            "Identified and recovered ₹6L in duplicate-payment errors through a payables review.",
            "Ensured on-time GST and tax filings for 3 entities with zero penalties.",
        ],
        "mistakes": [
            "Vague 'maintained accounts' with no accuracy, savings, or efficiency metrics.",
            "No software signals (Tally, QuickBooks, Excel) that ATS and recruiters scan for.",
            "Ignoring compliance results (audits passed, filings on time).",
        ],
        "blog": "accountant-resume-2026",
    },
    "fresher-first-job": {
        "role": "Fresher / First Job (No Experience)",
        "title": "Resume Examples for First Job & Freshers (2026) | theTailorCV",
        "description": "Resume examples for your first job with no experience — what to put in skills, projects, and bullet points, plus the ATS keywords and mistakes to avoid.",
        "intro": "No experience? Your first-job resume wins on projects, internships, coursework, and skills — framed with real outcomes, not just a list of subjects.",
        "skills": ["Projects", "Internships", "Relevant coursework", "Technical skills", "Tools you've used", "Certifications", "Teamwork", "Communication", "Problem solving", "Portfolio link"],
        "keywords": ["entry level", "fresher", "internship", "academic projects", "relevant coursework", "technical skills", "certifications", "no experience", "career objective", "portfolio"],
        "bullets": [
            "Built a full-stack expense-tracker app (React, Node) used by 40+ classmates — shipped, not just submitted.",
            "Completed a 2-month data internship; automated a weekly report, saving the team ~5 hours a week.",
            "Led a 4-person final-year project to a department award, owning the backend and database design.",
            "Earned the Google Data Analytics certificate and applied it to a real Kaggle dataset end-to-end.",
        ],
        "mistakes": [
            "Leaving the resume empty because of 'no experience' — projects and internships count.",
            "Listing coursework with no outcomes; show what you built or achieved.",
            "No project links or portfolio — for freshers, proof beats claims.",
        ],
        "blog": "how-to-get-a-job-with-no-experience-10-strategies-that-actually-work-in-2026",
    },
    "software-engineer": {
        "role": "Software Engineer",
        "title": "Software Engineer Resume Example & Guide (2026) | theTailorCV",
        "description": "A software engineer resume example with the right ATS keywords, skills, and bullet points that prove engineering impact — for new grads to senior roles.",
        "intro": "A software engineer resume should prove impact: systems you built, problems you solved, and the metrics that moved — not just a list of languages.",
        "skills": ["Data structures & algorithms", "Python", "Java", "JavaScript", "System design", "SQL", "Git", "REST APIs", "Testing", "CI/CD"],
        "keywords": ["software engineer", "data structures", "algorithms", "system design", "REST API", "unit testing", "CI/CD", "agile", "Git", "scalability"],
        "bullets": [
            "Designed and shipped a feature used by 100K+ users, cutting a core workflow from 5 steps to 2.",
            "Reduced API latency 40% by profiling hot paths and adding caching.",
            "Wrote the test suite that lifted coverage from 35% to 85%, catching regressions before release.",
            "Mentored 2 interns and led code reviews that reduced production incidents 25%.",
        ],
        "mistakes": [
            "Listing languages without impact, scale, or system-design decisions.",
            "No metrics — reviewers can't gauge the size of your work.",
            "Skipping DSA/system-design signals that many companies screen for.",
        ],
        "blog": "software-engineer-resume-faang",
    },
    "react-developer": {
        "role": "React Developer",
        "title": "React Developer Resume Example & Guide (2026) | theTailorCV",
        "description": "A React developer resume example with React/TypeScript keywords, key skills, and bullet points that show component architecture and performance wins.",
        "intro": "A React resume should show strong component architecture, state management, and performance — with shipped, clickable UIs.",
        "skills": ["React", "TypeScript", "Next.js", "Redux", "React Query", "Hooks", "Jest", "Tailwind", "Web performance", "REST & GraphQL"],
        "keywords": ["React", "TypeScript", "Next.js", "Redux", "hooks", "component architecture", "state management", "web performance", "REST API", "unit testing"],
        "bullets": [
            "Architected a React + TypeScript app with a 40-component design system reused across 4 products.",
            "Cut re-renders and bundle size 30% via memoization and code-splitting, improving Time to Interactive.",
            "Migrated class components to hooks, removing 6K lines and speeding feature delivery.",
            "Built reusable data-fetching with React Query, eliminating a class of loading/error bugs.",
        ],
        "mistakes": [
            "No live demos — React work should be clickable.",
            "Listing React with no architecture, state, or performance specifics.",
            "Ignoring TypeScript, now expected in most React roles.",
        ],
        "blog": "react-developer-resume-2026",
    },
    "ux-designer": {
        "role": "UX Designer",
        "title": "UX Designer Resume Example & Guide (2026) | theTailorCV",
        "description": "A UX designer resume example with design keywords, core skills, and bullet points framed around user outcomes and metrics — plus a portfolio link.",
        "intro": "A UX resume should pair a strong portfolio with bullets that show research-driven design and measurable user outcomes.",
        "skills": ["Figma", "User research", "Wireframing", "Prototyping", "Usability testing", "Design systems", "Interaction design", "Information architecture", "Accessibility", "A/B testing"],
        "keywords": ["UX design", "Figma", "user research", "usability testing", "wireframing", "prototyping", "design system", "information architecture", "accessibility", "user flows"],
        "bullets": [
            "Redesigned onboarding from research insights, lifting activation 21% in an A/B test.",
            "Ran 15 usability sessions that reshaped the checkout flow and cut support tickets 18%.",
            "Built a Figma design system adopted by 3 product teams, speeding design-to-dev handoff 40%.",
            "Improved accessibility to WCAG AA, expanding usable reach across assistive tech.",
        ],
        "mistakes": [
            "No portfolio link — UX is judged on the work and case studies.",
            "Showing screens with no research, rationale, or outcomes.",
            "Listing tools without the impact your design decisions drove.",
        ],
        "blog": "ux-designer-resume-2026",
    },
}
