// src/autofill/match.js — pure logic, no DOM needed.
//
// The option-matching and label-equivalence cases are ports of the assertions
// in test_field_registry.py: those encode bugs that already reached production
// once in the server engine, and the extension would reproduce every one of
// them if these rules drifted.
//
// Run: node test/match.test.mjs

import { readFileSync } from 'node:fs';
import { test, run, ok, notOk, eq, deepEq } from './harness.mjs';
import * as m from '../src/autofill/match.js';

// ── normalisation ────────────────────────────────────────────

test('questionSignature lowercases, strips punctuation and collapses space', () => {
  eq(m.questionSignature('  What IS your   Gender-Identity? '), 'what is your gender identity');
});

test('questionSignature caps at 160 chars', () => {
  eq(m.questionSignature('a'.repeat(400)).length, 160);
});

test('questionSignature of nothing is empty', () => {
  eq(m.questionSignature(null), '');
  eq(m.questionSignature(undefined), '');
  eq(m.questionSignature('   '), '');
});

// ── commitMatches (ported: browser.py _commit_matches) ───────

test('commitMatches accepts decoration around the wanted value', () => {
  ok(m.commitMatches('India', 'India (+91)'));
  ok(m.commitMatches('India (+91)', 'India'));
  ok(m.commitMatches('Yes', 'Yes'));
});

test('commitMatches does NOT match India against British Indian Ocean Territory', () => {
  // The exact production failure: a substring test passes here and picks the
  // wrong country.
  notOk(m.commitMatches('India', 'British Indian Ocean Territory (+246)'));
});

test('commitMatches does not confuse neighbouring countries', () => {
  notOk(m.commitMatches('India', 'Indonesia (+62)'));
  notOk(m.commitMatches('Austria', 'Australia'));
});

test('commitMatches rejects an empty widget', () => {
  notOk(m.commitMatches('India', ''));
  notOk(m.commitMatches('India', null));
});

test('commitMatches is permissive when nothing was requested', () => {
  ok(m.commitMatches('', 'anything'));
});

test('commitMatches ignores case and punctuation', () => {
  ok(m.commitMatches('decline to self-identify', 'Decline To Self Identify'));
});

// ── similarity ───────────────────────────────────────────────

test('similarity handles the degenerate cases', () => {
  eq(m.similarity('abc', 'abc'), 1);
  eq(m.similarity('', ''), 1);
  eq(m.similarity('abc', ''), 0);
  eq(m.similarity(null, null), 1);
});

test('similarity agrees with Python difflib exactly', () => {
  // OPTION_MATCH_THRESHOLD (0.55) is a number tuned against
  // difflib.SequenceMatcher on the server side, so this implementation has to
  // BE that measure, not merely resemble it. The first version used a
  // longest-common-subsequence ratio and scored "canada" against "india" at
  // 0.55 where difflib says 0.18 — i.e. it turned "nothing fits, ask the user"
  // into a confident wrong answer.
  //
  // fixtures/difflib-ratios.json is generated by Python; regenerate with:
  //   python -c "import difflib,json; ..."  (see the file's provenance in git)
  const rows = JSON.parse(
    readFileSync(new URL('./fixtures/difflib-ratios.json', import.meta.url), 'utf8'));
  ok(rows.length > 300, `fixture too small: ${rows.length}`);
  const bad = [];
  for (const [a, b, expected] of rows) {
    const got = m.similarity(a, b);
    if (Math.abs(got - expected) > 1e-9) bad.push(`${a!==b?`${a} / ${b}`:a}: ${got} != ${expected}`);
  }
  eq(bad.length, 0, `${bad.length}/${rows.length} disagree:\n    ${bad.slice(0, 5).join('\n    ')}`);
});

test('similarity separates the adversarial near-misses difflib does', () => {
  ok(m.similarity('canada', 'india') < 0.3, 'unrelated words must score low');
  ok(m.similarity('india', 'indonesia') < m.similarity('austria', 'australia'));
});

// ── bestOptionMatch ──────────────────────────────────────────

const OPTS = ['USA', 'Canada', 'Located Elsewhere'];

test('bestOptionMatch takes an exact normalised match outright', () => {
  eq(m.bestOptionMatch('canada', OPTS), 'Canada');
});

test('bestOptionMatch returns null rather than a wrong click', () => {
  eq(m.bestOptionMatch('Kolkata, India', OPTS), null,
     'no listed option fits, so nothing may be chosen');
});

test('bestOptionMatch handles {value,label} options', () => {
  const opts = [{ value: 'US', label: 'United States' }, { value: 'IN', label: 'India' }];
  deepEq(m.bestOptionMatch('India', opts), { value: 'IN', label: 'India' });
});

test('bestOptionMatch uses the containment floor for decline wordings', () => {
  const opts = ['I decline to self-identify', 'Male', 'Female'];
  eq(m.bestOptionMatch('Decline to self-identify', opts), 'I decline to self-identify');
});

test('bestOptionMatch on an empty list or empty value is null', () => {
  eq(m.bestOptionMatch('x', []), null);
  eq(m.bestOptionMatch('', OPTS), null);
});

test('bestOptionMatch will pick Australia for Austria, and verification catches it', () => {
  // Austria/Australia scores 0.875, comfortably over the 0.55 threshold, so the
  // ratio alone DOES pick it. Asserted rather than wished away: this is exactly
  // why commitMatches (whole-word, no ratio) is the layer that verifies what
  // actually landed in the widget, and why a mismatch there is reported as
  // "needs your review" instead of being trusted.
  eq(m.bestOptionMatch('Austria', ['Australia']), 'Australia');
  notOk(m.commitMatches('Austria', 'Australia'),
        'verification is the layer that catches this');
});

test('bestOptionMatch does not pick an unrelated country', () => {
  eq(m.bestOptionMatch('India', ['Canada', 'Brazil', 'Mexico']), null);
});

// ── looksLikeDecline ─────────────────────────────────────────

test('looksLikeDecline covers the real-world wordings', () => {
  for (const s of [
    'Decline to self-identify',
    'I prefer not to say',
    'I would rather not answer',
    'I do not wish to disclose',
    'I do not want to answer',      // GitLab's actual wording
    "I don't wish to answer",
    'Prefer not to disclose',
  ]) ok(m.looksLikeDecline(s), `should flag: ${s}`);
});

test('real answers are not mistaken for declines', () => {
  for (const s of [
    'Yes', 'No', 'Male', 'Female', 'I am not a protected veteran',
    'I am a veteran', 'White', 'Asian', 'No, I do not have a disability',
  ]) notOk(m.looksLikeDecline(s), `should NOT flag: ${s}`);
});

test('findDeclineOption picks the decline row out of a real option list', () => {
  const opts = ['I am a protected veteran', 'I am not a protected veteran',
                'I do not wish to answer'];
  eq(m.findDeclineOption(opts), 'I do not wish to answer');
  eq(m.findDeclineOption(['Male', 'Female']), null);
});

// ── labelsMatch (ported: runner.py _labels_match) ────────────

test('labelsMatch treats a question form as the same question', () => {
  ok(m.labelsMatch('Gender identity', 'What is your gender identity?'));
});

test('labelsMatch ignores a required marker and an optional suffix', () => {
  ok(m.labelsMatch('First Name *', 'First name (optional)'));
});

test('EEO labels differing by one word are NOT conflated', () => {
  // These score ~0.85 on a similarity ratio. Conflating them would drop a
  // genuinely empty required field, or fill it with the wrong answer.
  notOk(m.labelsMatch('What is your military status?', 'What is your disability status?'));
  notOk(m.labelsMatch('Gender', 'Gender pronouns') === true
        && m.labelsMatch('Gender', 'Gender pronouns'),
        'single distinctive word must not match broadly');
});

test('work authorization and sponsorship are not conflated', () => {
  notOk(m.labelsMatch(
    'Are you legally authorized to work in the United States?',
    'Will you now or in the future require sponsorship to work in the United States?'));
});

test('a stopword-only label never matches', () => {
  notOk(m.labelsMatch('What is your', 'What are you'));
});

test('a one-distinctive-word label never matches broadly', () => {
  notOk(m.labelsMatch('Name', 'Name of your previous employer'));
});

test('labelsMatch is false for empty input', () => {
  notOk(m.labelsMatch('', 'anything'));
  notOk(m.labelsMatch('anything', ''));
});

// ── document slots ───────────────────────────────────────────

test('documentSlotFor covers real label wordings', () => {
  eq(m.documentSlotFor('Resume/CV *'), 'resume');
  eq(m.documentSlotFor('Attach your resume'), 'resume');
  eq(m.documentSlotFor('Curriculum Vitae'), 'resume');
  eq(m.documentSlotFor('Cover Letter'), 'cover_letter');
  eq(m.documentSlotFor('CoverLetter'), 'cover_letter');
  eq(m.documentSlotFor('Writing Sample'), null, 'we never attach this one');
  eq(m.documentSlotFor('Portfolio'), null);
});

// ── the sensitive lock: the structural safety property ───────
//
// This is the table that decides whether the extension can ever fabricate a
// legal declaration. It gets the most cases of anything here, and it errs
// toward flagging on purpose.

const MUST_FLAG = [
  ['work_authorization', 'Are you legally authorized to work in the United States?'],
  ['work_authorization', 'Are you authorized to work in the country of employment?'],
  ['work_authorization', 'Do you have the legal right to work in the UK?'],
  ['work_authorization', 'Work authorization status'],
  ['work_authorization', 'Employment eligibility'],
  ['work_authorization', 'Are you eligible to work in Canada?'],
  ['sponsorship', 'Will you now or in the future require sponsorship?'],
  ['sponsorship', 'Do you require visa sponsorship to work in the US?'],
  ['sponsorship', 'Will you require sponsorship for employment visa status?'],
  ['sponsorship', 'Do you now or will you in the future require an H1B?'],
  ['sponsorship', 'What is your current visa status?'],
  ['sponsorship', 'Are you on OPT?'],
  ['citizenship', 'Are you a US citizen?'],
  ['citizenship', 'What is your nationality?'],
  ['citizenship', 'Are you a permanent resident?'],
  ['citizenship', 'Do you hold a green card?'],
  ['clearance', 'Do you have an active security clearance?'],
  ['clearance', 'What is your clearance level?'],
  ['criminal', 'Have you ever been convicted of a felony?'],
  ['criminal', 'Do you consent to a background check?'],
  ['criminal', 'Any criminal history?'],
  ['salary', 'What are your salary expectations?'],
  ['salary', 'Desired salary'],
  ['salary', 'Expected compensation'],
  ['salary', 'Current salary'],
  ['salary', 'What is your expected CTC?'],
  ['salary', 'Desired pay rate'],
  ['salary', 'What is your compensation requirement?'],
  ['demographic', 'What is your gender?'],
  ['demographic', 'Gender identity'],
  ['demographic', 'Race / Ethnicity'],
  ['demographic', 'What is your ethnicity?'],
  ['demographic', 'Are you Hispanic or Latino?'],
  ['demographic', 'Veteran status'],
  ['demographic', 'Protected veteran status'],
  ['demographic', 'Are you a protected military veteran?'],
  ['demographic', 'Disability status'],
  ['demographic', 'Do you have a disability?'],
  ['demographic', 'What are your pronouns?'],
  ['demographic', 'Do you identify as LGBTQ+?'],
  ['demographic', 'Sexual orientation'],
];

test('classifySensitive flags every real-world sensitive wording', () => {
  // Being flagged AT ALL is the safety property — the category only chooses
  // which sentence the sidebar shows. Asserted separately so that a wording
  // which reasonably belongs to two categories ("Do you hold a valid work
  // permit?" is both sponsorship and work authorization) can never be the
  // reason this test goes red and gets loosened.
  const missed = MUST_FLAG.filter(([, label]) => !m.classifySensitive(label))
                          .map(([, label]) => label);
  eq(missed.length, 0, `NOT FLAGGED:\n    ${missed.join('\n    ')}`);
});

test('classifySensitive assigns the expected category', () => {
  const wrong = [];
  for (const [expected, label] of MUST_FLAG) {
    const got = m.classifySensitive(label);
    if (got && got !== expected) wrong.push(`${label} -> ${got}, expected ${expected}`);
  }
  eq(wrong.length, 0, wrong.join('\n    '));
});

test('a question that is both sponsorship and authorization is still locked', () => {
  ok(m.classifySensitive('Do you hold a valid work permit?'));
  ok(m.classifySensitive('Do you have the right to work here without sponsorship?'));
});

test('classifySensitive leaves ordinary questions alone', () => {
  const flagged = [];
  for (const label of [
    'First name', 'Last name', 'Email address', 'Phone number',
    'LinkedIn profile', 'GitHub URL', 'Portfolio', 'City', 'State', 'Country',
    'Zip code', 'University', 'Degree', 'Major', 'Graduation date', 'GPA',
    'Current company', 'Current job title', 'Years of experience',
    'Notice period', 'When can you start?', 'Are you willing to relocate?',
    'How did you hear about us?', 'Why do you want to work here?',
    'Tell us about yourself', 'Do you agree to the terms and conditions?',
    'Would you like to receive marketing emails?', 'Key skills',
    'What is your preferred name?', 'Website',
  ]) {
    const got = m.classifySensitive(label);
    if (got) flagged.push(`${label} -> ${got}`);
  }
  eq(flagged.length, 0, `over-flagged:\n    ${flagged.join('\n    ')}`);
});

test('relocation is not treated as a sensitive question', () => {
  // It reads like an eligibility question but is a preference the user stated.
  eq(m.classifySensitive('Are you willing to relocate to New York?'), null);
});

test('isNeverFill covers identifiers we must not touch at all', () => {
  for (const label of [
    'Social Security Number', 'SSN', 'National Insurance number',
    'Bank account number', 'Routing number', 'IBAN', 'Credit card number', 'CVV',
    'Password', 'One time password', 'Date of birth', 'DOB', 'Birth date',
    'PAN card number', 'Aadhaar number',
  ]) ok(m.isNeverFill(label), `should be never-fill: ${label}`);
});

test('isNeverFill does not catch ordinary fields', () => {
  for (const label of ['Phone number', 'Employee ID at current company',
                       'Account manager name', 'Graduation date']) {
    notOk(m.isNeverFill(label), `should be fillable: ${label}`);
  }
});

test('looksSecret flags secret-shaped values', () => {
  ok(m.looksSecret('123-45-6789'));
  ok(m.looksSecret('4111 1111 1111 1111'));
  ok(m.looksSecret('GB82WEST12345698765432'));
  notOk(m.looksSecret('Ada Lovelace'));
  notOk(m.looksSecret('+91 98765 43210'));
  notOk(m.looksSecret(''));
});

// ── splitPhone ───────────────────────────────────────────────

test('splitPhone separates a dial code from the national number', () => {
  deepEq(m.splitPhone('+91 98765 43210'),
         { dialCode: '+91', national: '9876543210', e164: '+919876543210' });
  deepEq(m.splitPhone('+1 (415) 555-0123'),
         { dialCode: '+1', national: '4155550123', e164: '+14155550123' });
});

test('splitPhone leaves a number with no dial code untouched', () => {
  deepEq(m.splitPhone('9876543210'),
         { dialCode: '', national: '9876543210', e164: '9876543210' });
});

test('splitPhone prefers the longest matching dial code', () => {
  eq(m.splitPhone('+971501234567').dialCode, '+971');
  eq(m.splitPhone('+35312345678').dialCode, '+353');
});

test('splitPhone on junk returns it unchanged', () => {
  deepEq(m.splitPhone(''), { dialCode: '', national: '', e164: '' });
});

// ── dates ────────────────────────────────────────────────────

test('parseLooseDate reads the shapes resumes actually contain', () => {
  deepEq(m.parseLooseDate('2024-06-01'), { y: 2024, m: 6, d: 1 });
  deepEq(m.parseLooseDate('2024-06'), { y: 2024, m: 6, d: 1 });
  deepEq(m.parseLooseDate('06/2024'), { y: 2024, m: 6, d: 1 });
  deepEq(m.parseLooseDate('Jun 2024'), { y: 2024, m: 6, d: 1 });
  deepEq(m.parseLooseDate('June 2024'), { y: 2024, m: 6, d: 1 });
  deepEq(m.parseLooseDate('June 1, 2024'), { y: 2024, m: 6, d: 1 });
  deepEq(m.parseLooseDate('1 June 2024'), { y: 2024, m: 6, d: 1 });
  deepEq(m.parseLooseDate('2024'), { y: 2024, m: 1, d: 1 });
});

test('parseLooseDate reads an unambiguous day-first date correctly', () => {
  deepEq(m.parseLooseDate('25/06/2024'), { y: 2024, m: 6, d: 25 });
  deepEq(m.parseLooseDate('06/25/2024'), { y: 2024, m: 6, d: 25 });
});

test('parseLooseDate refuses what it cannot read', () => {
  eq(m.parseLooseDate('Present'), null);
  eq(m.parseLooseDate('ASAP'), null);
  eq(m.parseLooseDate('sometime next spring'), null);
  eq(m.parseLooseDate(''), null);
  eq(m.parseLooseDate('2024-13-01'), null, 'month 13 is not a date');
});

test('formatDateForField respects an ISO date input', () => {
  eq(m.formatDateForField('Jun 2024', { type: 'date' }), '2024-06-01');
  eq(m.formatDateForField('Jun 2024', { type: 'month' }), '2024-06');
});

test('formatDateForField takes its shape from the placeholder', () => {
  eq(m.formatDateForField('2024-06-15', { placeholder: 'MM/DD/YYYY' }), '06/15/2024');
  eq(m.formatDateForField('2024-06-15', { placeholder: 'DD/MM/YYYY' }), '15/06/2024');
  eq(m.formatDateForField('2024-06-15', { placeholder: 'YYYY-MM-DD' }), '2024-06-15');
  eq(m.formatDateForField('2024-06-15', { placeholder: 'MM/YYYY' }), '06/2024');
});

test('formatDateForField returns empty rather than garbage', () => {
  eq(m.formatDateForField('whenever', { type: 'date' }), '',
     'an unparseable date must leave the field for the user');
  eq(m.formatDateForField('', {}), '');
});

// ── field synonyms ───────────────────────────────────────────

test('matchFieldKey resolves the common identity fields', () => {
  eq(m.matchFieldKey('First Name *').key, 'first_name');
  eq(m.matchFieldKey('What is your last name?').key, 'last_name');
  eq(m.matchFieldKey('Email Address').key, 'email');
  eq(m.matchFieldKey('Mobile number').key, 'phone');
  eq(m.matchFieldKey('LinkedIn Profile URL').key, 'linkedin_url');
});

test('matchFieldKey resolves education fields', () => {
  eq(m.matchFieldKey('University / College').key, 'university');
  eq(m.matchFieldKey('Field of Study').key, 'major');
  eq(m.matchFieldKey('CGPA').key, 'gpa');
  eq(m.matchFieldKey('Expected graduation date').key, 'graduation_date');
});

test('matchFieldKey resolves address parts individually', () => {
  eq(m.matchFieldKey('City').key, 'address_city');
  eq(m.matchFieldKey('State / Province').key, 'address_state');
  eq(m.matchFieldKey('Zip Code').key, 'postal_code');
  eq(m.matchFieldKey('Country').key, 'address_country');
});

test('matchFieldKey marks the sensitive entries as sensitive', () => {
  const wa = m.matchFieldKey('Are you legally authorized to work in the United States?');
  eq(wa.key, 'authorized_to_work_in_country');
  ok(wa.sensitive);
  const sp = m.matchFieldKey('Will you now or in the future require sponsorship?');
  eq(sp.key, 'requires_visa_sponsorship');
  ok(sp.sensitive);
});

test('matchFieldKey does not conflate work authorization with sponsorship', () => {
  const a = m.matchFieldKey('Are you legally authorized to work in the US?');
  const b = m.matchFieldKey('Do you require visa sponsorship?');
  eq(a.key, 'authorized_to_work_in_country');
  eq(b.key, 'requires_visa_sponsorship');
});

test('matchFieldKey prefers the more specific synonym', () => {
  eq(m.matchFieldKey('Gender').key, 'gender');
  eq(m.matchFieldKey('Preferred pronouns').key, 'gender_pronouns');
  eq(m.matchFieldKey('Current company').key, 'current_company');
  eq(m.matchFieldKey('Current job title').key, 'current_job_title');
});

test('matchFieldKey returns null for a question it has no key for', () => {
  eq(m.matchFieldKey('Have you ever used Robinhood?'), null);
  eq(m.matchFieldKey('Which of our products do you use most?'), null);
  eq(m.matchFieldKey(''), null);
});

test('every sensitive FIELD_SYNONYMS entry is also caught by classifySensitive', () => {
  // Belt and braces: the two mechanisms are independent, and a synonym marked
  // sensitive that classifySensitive misses would be fillable by the LLM tier.
  const gaps = [];
  for (const entry of m.FIELD_SYNONYMS) {
    if (!entry.sensitive) continue;
    for (const label of entry.labels) {
      if (!m.classifySensitive(label)) gaps.push(`${entry.key}: ${label}`);
    }
  }
  eq(gaps.length, 0, `sensitive synonyms not flagged:\n    ${gaps.join('\n    ')}`);
});

test('no non-sensitive synonym is flagged sensitive', () => {
  // The inverse gap: a synonym NOT marked sensitive that classifySensitive
  // flags would be permanently unanswerable, since the deterministic tier
  // would refuse it and the LLM would never see it.
  const gaps = [];
  for (const entry of m.FIELD_SYNONYMS) {
    if (entry.sensitive) continue;
    for (const label of entry.labels) {
      const cat = m.classifySensitive(label);
      if (cat) gaps.push(`${entry.key}: "${label}" -> ${cat}`);
    }
  }
  eq(gaps.length, 0, `unanswerable synonyms:\n    ${gaps.join('\n    ')}`);
});

test('isPlaceholderOption spots the non-answers', () => {
  ok(m.isPlaceholderOption('Select…'));
  ok(m.isPlaceholderOption('Select an option'));
  ok(m.isPlaceholderOption('Please select'));
  ok(m.isPlaceholderOption('Choose one'));
  ok(m.isPlaceholderOption('---'));
  notOk(m.isPlaceholderOption('Yes'));
  notOk(m.isPlaceholderOption('Selected candidate'));
});

await run('match.js');
